version: "3"
services:
  database:
    image: mysql:8.0.20
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: chd
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: chd
      MYSQL_PASSWORD: chd1234!
      TZ: "Asia/Seoul"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ../docker/mysql_volume:/var/lib/mysql/
#  core:
#    build: '',
#    restart: always
#    container_name: "core"
#    ports:
#      - "8443:8443" # When you use HTTPS
#      - "8080:8080" # When you use HTTP
#    networks:
#      - backend
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#    volumes:
#      - <local path>:<docker path>
