server:
  port: 8080
  undertow:
    io-threads: 4
    worker-threads: 32
    buffer-size: 1024
    direct-buffers: true

---
spring:
  profiles:
    active: prod

---

spring:
  profiles:
    active: dev

---

spring:
  profiles:
    active: local